package:
  name: OpenMM-Systems
  version: 0.0.0a0.dev0

source:
  fn: openmm_systems-0.0.0a0.dev0.tar.gz
  url: https://github.c/{{ version }}/{{ name }}-{{ version }}.tar.gz
  # TODO: way to specify a hole or 
  sha256:

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - openmm_systems = openmm_systems.cli:cli

requirements:
  build:
    - python
    - setuptools
    - wheel

  host:
    - python
    
  run:
    - python
    

about:
  home: https://github.com/ADicksonLab/OpenMM-Systems.git
  license: MIT
  license_file: LICENSE
  summary: "Collection of premade molecular systems for use with OpenMM"
  doc_url: https://adicksonlab.github.io/openmm_systems
  dev_url: https://github.com/ADicksonLab/OpenMM-Systems.git

extra:
  recipe-maintainers:
    - salotz
